language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
services:
  - mongodb
addons:
  sauce_connect:
    username: "yc-f15"
    access_key:
      secure: "hIeFc5y/OZ9x6q7I03Jxwc/19yAQs8ANgZgUK8D/HG0tk89flcBi1hNGxOd/Lc4dNf0PrnwWqMLKcFj104kgYuEMmw2KO/1Wgp4Ke+eGV0gy/hU3ji52uElAJesRaqj1s2HvcjZGBv2F/XbY7xVBsokhqOSAw89g5NTZEgwsNXt3rRD7ZE29VdRbLoRg40cP+SJZskRGRJDCoUhyD/1FSXVmJwMt39qWCVerj0zkOxRPklZh8bnUwTZDb2P8oQmsTUJli4DmO+XTC9OyVKFPB/47CDFiBl9/fsJjRBi8DQeyisoF3XgVtCqK9kMogkeDo7RzqQaqFt12zD5MZFo/Sa2jaRSNlExws451OWScbLwmDPqoaokHaPDC4bKNbCD+wd+uBAhP43zWVA5Ug10TtG+Mzq8kARYgeMAPULI0atVLRO9X5xlmKBM5piPVjWLTNWK15qvsGNNzdMWdxNWPlVmhK7wTDlcSs4fiJUzcIqndEfHeUeKXFXbRsTmqajEzaLof3sb2MKWPYfjafjVgDpViqgXIdRHmZ0LdEQV1vsH0PSTWDycOxHSrtGbj/VynvCx1OMRckj/yq4/8EO1mP0NYBt3wadvqv3O+0+rkk9w7aTgogvxacgl+DdoSsLAxSECI90pGGdREqjPxsp5mE4uTV6IzGsr5Nn2QlzevoB0="
